### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by wasimreja** [Kajal13081/MusicApp#63]

**Comment by wasimreja** [comment]
@Kajal13081 I would like to work on this under JWoC.

**Comment by Kajal13081** [comment]
Sure. All the best.

**Comment by wasimreja** [comment]
#65

**Comment by wasimreja** [comment]
Updated README.md file  #66

**Comment by codervivek5** [comment]
I want to work in this issue....I will update readme file according to project instruction...that is easy for every person who read README.md file

**Comment by Kajal13081** [comment]
Sure @codervivek5 Go ahead. And also add the app apk link in readme.

**Comment by aritra-tech** [comment]
I would like to work on this under JWoC.

**Comment by Kajal13081** [comment]
@codervivek5 what's the update?
