### ISSUE TITLE
Add Audio Visualizer

### ISSUE THREAD

**Issue by Kajal13081** [Kajal13081/MusicApp#83]
Reference:
https://github.com/gauravk95/audio-visualizer-android

**Comment by ken1000minus7** [comment]
I would like to work on this issue under JWOC ✌️  . Where should this appear, with the music image in the player view I believe?

**Comment by Kajal13081** [comment]
> I would like to work on this issue under JWOC ✌️ . Where should this appear, with the music image in the player view I believe?

Yes @ken1000minus7
